version: "3.9"

services:
  api-1:
    build:
      context: .
      dockerfile: "SearchAPI/Dockerfile"
    ports:
      - "4444:80"
    volumes:
      - E:/Work/LargeSystems/data:/data
  web:
    build:
       context: .
       dockerfile: "SearchApplication/Dockerfile"
    ports:
       - "4445:80"